export const LESION_CLASSIFICATION = {
    ulcer: "ulcer",
    centralLesion: "central_lesion",
    naturalChanges: "natural_changes",
    painDisturbance: "pain_disturbance",
    whiteLesion: "white_lesion",
    infectiousLesion: "infectious_lesion",
    dentalChanges: "dental_changes",
    temporomandibularDisturbance: "temporomandibular_disturbance",
    pigmantedLesion: "pigmanted_lesion",
    gingivalHyperplasia: "gingival_hyperplasia",
    syndrome: "syndrome",
    cervicalLumps: "cervical_lumps",
    prominentLesion: "prominent_lesion",
    salivaryLesion: "salivary_lesion",
    complicatedDisease: "complicated_disease",
};
