export const NOTIFICATION_SUB_CATEGORIES = {
    LOGIN_SUCCEED: 111,
    LOGIN_FAILED: 112,
    SIGNUP_SUCCEED: 113,
    USER_EMAIL_VERIFIED: 121,
    USER_VERIFICATION_REQUESTED: 122,
    USER_VERIFICATION_VERIFIED: 123,
    USER_VERIFICATION_REJECTED: 124,
};
